from .auth_routes import auth_bp
from .cases_routes import cases_bp
from .evidence_routes import evidence_bp
from .custody_routes import custody_bp
from .hearings_routes import hearings_bp
from .documents_routes import documents_bp
from .submissions_routes import submissions_bp
from .dashboard_routes import dashboard_bp
from .activity_routes import activity_bp
from .notifications_routes import notifications_bp
from .users_routes import users_bp
from .settings_routes import settings_bp
